"use client";

import { useState } from "react";
import { Calculator, RotateCcw, PlayCircle } from "lucide-react";

export default function PaybackPeriodCalculator() {
  const [initialInvestment, setInitialInvestment] = useState("");
  const [cashFlow, setCashFlow] = useState("");
  const [mode, setMode] = useState("annual"); // annual or monthly

  const [paybackYears, setPaybackYears] = useState<number | null>(null);
  const [paybackMonths, setPaybackMonths] = useState<number | null>(null);

  const calculatePayback = () => {
    const investment = parseFloat(initialInvestment);
    const inflow = parseFloat(cashFlow);

    if (!investment || !inflow || investment <= 0 || inflow <= 0) return;

    let totalMonths;

    if (mode === "annual") {
      totalMonths = (investment / inflow) * 12;
    } else {
      totalMonths = investment / inflow;
    }

    const years = Math.floor(totalMonths / 12);
    const months = Math.round(totalMonths % 12);

    setPaybackYears(years);
    setPaybackMonths(months);
  };

  const tryExample = () => {
    setInitialInvestment("500000");
    setCashFlow("150000");
    setMode("annual");
    setTimeout(() => calculatePayback(), 100);
  };

  const resetFields = () => {
    setInitialInvestment("");
    setCashFlow("");
    setMode("annual");
    setPaybackYears(null);
    setPaybackMonths(null);
  };

  return (
    <div className="max-w-5xl mx-auto bg-white shadow-lg rounded-2xl p-8">
      <h1 className="text-3xl font-bold mb-6 flex items-center gap-2">
        <Calculator className="text-indigo-600" size={28} />
        Payback Period Calculator
      </h1>

      <div className="grid md:grid-cols-2 gap-6">

        <div>
          <label className="font-medium">Initial Investment (₹)</label>
          <input
            type="number"
            value={initialInvestment}
            onChange={(e) => setInitialInvestment(e.target.value)}
            placeholder="Enter investment amount"
            className="w-full border rounded-lg px-4 py-2 mt-2"
          />
        </div>

        <div>
          <label className="font-medium">
            {mode === "annual" ? "Annual Cash Inflow (₹)" : "Monthly Cash Inflow (₹)"}
          </label>
          <input
            type="number"
            value={cashFlow}
            onChange={(e) => setCashFlow(e.target.value)}
            placeholder="Enter cash inflow"
            className="w-full border rounded-lg px-4 py-2 mt-2"
          />
        </div>

        <div>
          <label className="font-medium">Cash Flow Type</label>
          <select
            value={mode}
            onChange={(e) => setMode(e.target.value)}
            className="w-full border rounded-lg px-4 py-2 mt-2"
          >
            <option value="annual">Annual</option>
            <option value="monthly">Monthly</option>
          </select>
        </div>

      </div>

      {/* Buttons - iSevenPlus Standard */}
      <div className="flex flex-col sm:flex-row gap-4 mt-8">
        <button
          onClick={calculatePayback}
          className="w-full sm:flex-1 bg-indigo-600 hover:bg-indigo-700 text-white py-3 rounded-lg font-semibold flex items-center justify-center gap-2">
          <Calculator size={18} />
          Calculate Payback Period
        </button>

        <button
          onClick={tryExample}
          className="w-full sm:flex-1 bg-green-500 hover:bg-green-600 text-white py-3 rounded-lg font-semibold flex items-center justify-center gap-2">
          <PlayCircle size={18} />
          Try Example
        </button>

        <button
          onClick={resetFields}
          className="w-full sm:flex-1 bg-gray-500 hover:bg-gray-600 text-white py-3 rounded-lg font-semibold flex items-center justify-center gap-2">
          <RotateCcw size={18} />
          Reset
        </button>
      </div>

      {paybackYears !== null && (
        <div className="mt-8 bg-gray-100 p-6 rounded-xl space-y-2">
          <h3 className="text-xl font-semibold mb-2">Payback Result</h3>
          <p>
            Payback Period:{" "}
            <strong>
              {paybackYears} Years {paybackMonths} Months
            </strong>
          </p>
        </div>
      )}

      {/* SEO Section */}
      <div className="mt-12 space-y-6 text-gray-700">
        <h2 className="text-2xl font-bold">What is Payback Period?</h2>
        <p>
          Payback period is the time required to recover the initial investment 
          from cash inflows generated by the project.
        </p>

        <h2 className="text-2xl font-bold">Payback Formula</h2>
        <p>
          <strong>
            Payback Period = Initial Investment / Annual Cash Inflow
          </strong>
        </p>

        <h2 className="text-2xl font-bold">Why Use This Calculator?</h2>
        <ul className="list-disc ml-6 space-y-2">
          <li>Investment decision making</li>
          <li>Project risk assessment</li>
          <li>Capital budgeting analysis</li>
          <li>Startup ROI planning</li>
        </ul>

        <h2 className="text-2xl font-bold">FAQs</h2>

        <div>
          <p className="font-semibold">1. Is shorter payback better?</p>
          <p>
            Yes, shorter payback periods generally indicate lower risk and faster recovery of investment.
          </p>
        </div>

        <div>
          <p className="font-semibold">2. Does this consider time value of money?</p>
          <p>
            No. This is a simple payback method. For advanced analysis use NPV or IRR.
          </p>
        </div>
      </div>
    </div>
  );
}