"use client";

import { useState, useRef, useEffect } from "react";
import { Moon, Download, Share2, Maximize2 } from "lucide-react";
import html2canvas from "html2canvas";

export default function SleepCycleCalculator() {
  const [sleepNowResults, setSleepNowResults] = useState<string[]>([]);
  const [wakeTimeInput, setWakeTimeInput] = useState("");
  const [sleepTimes, setSleepTimes] = useState<string[]>([]);
  const [fullscreen, setFullscreen] = useState(false);
  const [currentTime, setCurrentTime] = useState("");

  const cardRef = useRef<HTMLDivElement>(null);
  const storyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTime(new Date().toLocaleTimeString());
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const addMinutes = (date: Date, mins: number) =>
    new Date(date.getTime() + mins * 60000);

  const calculateSleepNow = () => {
    const now = addMinutes(new Date(), 15);
    const results = [4, 5, 6].map(cycles => {
      return addMinutes(now, cycles * 90).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    });
    setSleepNowResults(results);
  };

  const calculateWakeTime = () => {
    if (!wakeTimeInput) return;

    const [hour, minute] = wakeTimeInput.split(":");
    const wake = new Date();
    wake.setHours(Number(hour));
    wake.setMinutes(Number(minute));
    wake.setSeconds(0);

    const results = [6, 5, 4].map(cycles => {
      return addMinutes(wake, -(cycles * 90) - 15)
        .toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    });

    setSleepTimes(results);
  };

  const downloadImage = async () => {
    if (!cardRef.current) return;
    const canvas = await html2canvas(cardRef.current);
    const link = document.createElement("a");
    link.download = "sleep-cycle-iSevenPlus.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  const downloadStory = async () => {
    if (!storyRef.current) return;
    const canvas = await html2canvas(storyRef.current);
    const link = document.createElement("a");
    link.download = "sleep-cycle-story-iSevenPlus.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  const shareWhatsApp = () => {
    const text = "😴 Optimize your sleep cycle with iSevenPlus Sleep Calculator!";
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  return (
    <div className={`max-w-5xl mx-auto bg-white shadow-xl rounded-2xl p-6 md:p-10 ${fullscreen ? "fixed inset-0 z-50" : ""}`}>

      <h2 className="text-3xl font-bold text-center text-indigo-700 mb-8 flex items-center justify-center gap-2">
        <Moon className="animate-pulse" />
        Sleep Cycle Calculator
      </h2>

      <p className="text-center text-gray-500 mb-6">
        Current Time: {currentTime}
      </p>

      {/* Sleep Now */}
      <div className="bg-indigo-50 p-6 rounded-xl mb-6">
        <h3 className="font-semibold mb-4">If You Sleep Now 😴</h3>
        <button
          onClick={calculateSleepNow}
          className="bg-indigo-600 text-white px-6 py-2 rounded-lg"
        >
          Calculate Wake Up Time
        </button>

        {sleepNowResults.length > 0 && (
          <div className="mt-4 text-xl font-bold">
            Wake up at: {sleepNowResults.join(" | ")}
          </div>
        )}
      </div>

      {/* Wake At Specific Time */}
      <div className="bg-purple-50 p-6 rounded-xl mb-6">
        <h3 className="font-semibold mb-4">If You Want to Wake At ⏰</h3>
        <input
          type="time"
          value={wakeTimeInput}
          onChange={(e) => setWakeTimeInput(e.target.value)}
          className="border-2 border-purple-200 rounded-lg px-4 py-2"
        />
        <button
          onClick={calculateWakeTime}
          className="ml-4 bg-purple-600 text-white px-6 py-2 rounded-lg"
        >
          Calculate Sleep Time
        </button>

        {sleepTimes.length > 0 && (
          <div className="mt-4 text-xl font-bold">
            Sleep at: {sleepTimes.join(" | ")}
          </div>
        )}
      </div>

      {/* Result Card */}
      <div
        ref={cardRef}
        className="mt-6 p-8 rounded-2xl text-white text-center shadow-2xl"
        style={{
          background: "linear-gradient(180deg, #1e3a8a, #4338ca, #6366f1)"
        }}
      >
        <h3 className="text-3xl font-bold mb-4">Healthy Sleep = Better Life 🌙</h3>
        <p className="opacity-90">Each cycle is 90 minutes. Aim for 4-6 cycles.</p>
        <p className="mt-2 text-sm">Generated by iSevenPlus 😴</p>
      </div>

      {/* Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 mt-6">
        <button onClick={downloadImage} className="flex-1 bg-indigo-600 text-white py-3 rounded-xl flex justify-center gap-2">
          <Download size={18}/> Download
        </button>
        <button onClick={downloadStory} className="flex-1 bg-purple-600 text-white py-3 rounded-xl flex justify-center gap-2">
          <Download size={18}/> Instagram Story
        </button>
        <button onClick={shareWhatsApp} className="flex-1 bg-green-600 text-white py-3 rounded-xl flex justify-center gap-2">
          <Share2 size={18}/> Share
        </button>
        <button onClick={() => setFullscreen(!fullscreen)} className="flex-1 bg-gray-800 text-white py-3 rounded-xl flex justify-center gap-2">
          <Maximize2 size={18}/> Fullscreen
        </button>
      </div>

      {/* Hidden Story */}
      <div
        ref={storyRef}
        style={{
          position: "fixed",
          top: "-9999px",
          left: "-9999px",
          width: "1080px",
          height: "1920px",
          background: "linear-gradient(180deg, #1e3a8a, #4338ca, #6366f1)",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          color: "white",
          textAlign: "center",
          padding: "120px"
        }}
      >
        <h1 style={{fontSize:"100px", marginBottom:"40px"}}>Sleep Cycle</h1>
        <p style={{fontSize:"60px"}}>Optimize Your Rest 😴</p>
        <p style={{position:"absolute", bottom:"120px", fontSize:"40px", opacity:0.8}}>
          iSevenPlus 🌙
        </p>
      </div>

      {/* SEO */}
      <div className="mt-16">
        <h2 className="text-2xl font-bold mb-4">
          What is Sleep Cycle?
        </h2>
        <p className="text-gray-700 leading-relaxed">
          Sleep Cycle Calculator helps you plan your sleep based on 90-minute natural sleep cycles.
          Waking up at the end of a cycle makes you feel more refreshed.
        </p>
      </div>

    </div>
  );
}